=== gaborbsd/jhelioviewer-socis2012/conf/conf.dtd
<!ELEMENT configuration (global, entry+)>

<!ELEMENT global (stream-server, stream-port, stream-pass, stream-type, hvroot, urlbase, img-base)>

<!ELEMENT entry (mount-point, name, desc, observatory, instrument, detector, measurement, date?,
  fps, resolution, sec-per-img, palette?, dateformat?, region?, subchannels?)>

<!ELEMENT stream-server (#PCDATA)>
<!ELEMENT stream-port (#PCDATA)>
<!ELEMENT stream-pass (#PCDATA)>
<!ELEMENT stream-type (#PCDATA)>
<!ELEMENT hvroot (#PCDATA)>
<!ELEMENT urlbase (#PCDATA)>
<!ELEMENT img-base (#PCDATA)>

<!ELEMENT mount-point (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT desc (#PCDATA)>
<!ELEMENT observatory (#PCDATA)>
<!ELEMENT instrument (#PCDATA)>
<!ELEMENT detector (#PCDATA)>
<!ELEMENT measurement (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT fps (#PCDATA)>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT sec-per-img (#PCDATA)>
<!ELEMENT palette EMPTY>
<!ELEMENT dateformat (#PCDATA)>
<!ELEMENT subchannels (channel+)>
<!ELEMENT channel EMPTY>
<!ELEMENT region (top, left, height, width)>
<!ELEMENT top (#PCDATA)>
<!ELEMENT left (#PCDATA)>
<!ELEMENT height (#PCDATA)>
<!ELEMENT width (#PCDATA)>

<!ATTLIST entry	xml:id ID #IMPLIED
		mode (loop-dir|realtime|cyclic-day) #REQUIRED>

<!ATTLIST channel href IDREF #REQUIRED>

=== gaborbsd/jhelioviewer-socis2012/conf/conf.xml
<!DOCTYPE configuration PUBLIC "-//JHelioviewer//DTD Channel Configuration//EN"
  "conf.dtd">
<configuration>
  <global>
    <stream-server>150.214.150.68</stream-server>
    <stream-port>4551</stream-port>
    <stream-pass>changeme</stream-pass>
    <stream-type>video/ogg</stream-type>
    <kakadupath>/home/gabor/bin</kakadupath>
    <tmpdir>/home/gabor/tmp</tmpdir>
    <hvroot>/home/gabor</hvroot>
    <urlbase>http://kovesdan.org/jhv</urlbase>
    <img-base>/home/gabor/img/delphi.nascom.nasa.gov/jp2</img-base>
  </global>

  <entry xml:id="full2048">
    <name>Full 2048x2048 - May 26</name>
    <desc>Full image of the Sun in 2048x2048 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>2048</resolution>
    <duration>25</duration>
  </entry>

  <entry xml:id="full1024">
    <name>Full 1024x1024 - May 26</name>
    <desc>Full image of the Sun in 1024x1024 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>1024</resolution>
    <duration>25</duration>
  </entry>
  
  <entry xml:id="full512">
    <mount-point>full512.ogg</mount-point>
    <name>Full 512x512 - May 26</name>
    <desc>Full image of the Sun in 512x512 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>512</resolution>
    <duration>25</duration>
    <palette/>
    <dateformat>+%Y-%m-%d %H:%M:%S</dateformat>
    <subchannels>
      <channel href="topleft512"/>
      <channel href="topright512"/>
      <channel href="bottomleft512"/>
      <channel href="bottomright512"/>
    </subchannels>
  </entry>

  <entry xml:id="topleft512">
    <name>Top-left 512x512 - May 26</name>
    <desc>Top-left view of the Sun in 512x512 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>1024</resolution>
    <duration>25</duration>
    <dateformat>+%Y-%m-%d %H:%M:%S</dateformat>
    <region>
      <top>0.0</top>
      <left>0.0</left>
      <height>0.5</height>
      <width>0.5</width>
    </region>
  </entry>

  <entry xml:id="topright512">
    <name>Top-right 512x512 - May 26</name>
    <desc>Top-right view of the Sun in 512x512 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>1024</resolution>
    <duration>25</duration>
    <dateformat>+%Y-%m-%d %H:%M:%S</dateformat>
    <region>
      <top>0.0</top>
      <left>0.5</left>
      <height>0.5</height>
      <width>0.5</width>
    </region>
  </entry>

  <entry xml:id="bottomleft512">
    <name>Bottom-left 512x512 - May 26</name>
    <desc>Bottom-left view of the Sun in 512x512 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>1024</resolution>
    <duration>25</duration>
    <region>
      <top>0.5</top>
      <left>0.0</left>
      <height>0.5</height>
      <width>0.5</width>
    </region>
  </entry>

  <entry xml:id="bottomright512">
    <name>Bottom-right 512x512 - May 26</name>
    <desc>Bottom-right view of the Sun in 512x512 resolution from 2012 May 26</desc>
    <observatory>SDO</observatory>
    <instrument>AIA</instrument>
    <detector>AIA</detector>
    <measurement>1600</measurement>
    <date>2012/05/26</date>
    <fps>25</fps>
    <resolution>1024</resolution>
    <duration>25</duration>
    <dateformat>+%Y-%m-%d %H:%M:%S</dateformat>
    <region>
      <top>0.5</top>
      <left>0.5</left>
      <height>0.5</height>
      <width>0.5</width>
    </region>
  </entry>
</configuration>
